### PR TITLE
Features/hdev 259 convert into tailwind

### PR DESCRIPTION
**Pull request by geonellov**
## Description of Changes
This PR converts the Epoch timer into Tailwind

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDEV-259)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
* [ ] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### CODE REVIEW

**Review by tracyarciaga — COMMENTED** [review]
@geonellov  In mobile view, the content of the epoch timer box is not centered
image

**Comment by geonellov** [comment]
> @geonellov In mobile view, the content of the epoch timer box is not centered image

@tracyarciaga Done fixing.

**Comment by tracyarciaga** [comment]
@geonellov please fix the conflicts in this PR

**Comment by schystz** [comment]
@geonellov can we merge this over to [features/hdev-576-setup-synchronization-and-automatic-fallback-to-hosted-service](https://github.com/HaloDAO/halodao-interface/pull/199)?

**Comment by geonellov** [comment]
> @geonellov can we merge this over to [features/hdev-576-setup-synchronization-and-automatic-fallback-to-hosted-service](https://github.com/HaloDAO/halodao-interface/pull/199)?

@schystz this is already in hdev-576

**Pull request closed without merging**
